---
- hosts: all
  remote_user: debian
  become: yes
  vars:
    source_files_directory: "/home/debian/ansible-files"

  tasks:
    - name: Check if user docker-system exists
      ansible.builtin.command: id docker-system
      register: user_check
      ignore_errors: true

    - name: Create system user docker-system if it does not exist
      ansible.builtin.user:
        name: docker-system
        system: yes
        group: docker
        shell: /sbin/nologin
      when: user_check.rc != 0
